export const adjectives = [
  {
    type: 'adjectives',
    word: 'amused',
    definition: 'thinking that somebody/something is funny, so that you smile or laugh',
    inSentence: "There was an amused look on the President's face.",
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'adjectives',
    word: 'anxious',
    definition: 'eeling worried or nervous',
    inSentence: 'The bus was late and Sue began to get anxious.',
    synonyms: 'worried',
    antonyms: '',
  },
  {
    type: 'adjectives',
    word: 'bloody',
    definition: 'a swear word that many people find offensive that is used to emphasize a comment or an angry statement',
    inSentence: "Don't be such a bloody fool.",
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'adjectives',
    word: 'brainy',
    definition: 'very intelligent',
    inSentence: 'He’s a brainy kid.',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'adjectives',
    word: 'busy',
    definition: 'having a lot to do; perhaps not free to do something else because you are working on something',
    inSentence: "I'm afraid the doctor is busy at the moment. Can he call you back?",
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'adjectives',
    word: 'charming',
    definition: 'very pleasant or attractive',
    inSentence: "The cottage is tiny, but it's charming.",
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'adjectives',
    word: 'comfortable',
    definition: '(of clothes, furniture, etc.) making you feel physically relaxed; pleasant to wear, sit on, etc.',
    inSentence: "It's such a comfortable bed.",
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'adjectives',
    word: 'creepy',
    definition: 'causing an unpleasant feeling of fear or slight horror',
    inSentence: "It's kind of creepy down in the cellar!",
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'adjectives',
    word: 'curious',
    definition: 'having a strong desire to know about something',
    inSentence: 'He is such a curious boy, always asking questions.',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'adjectives',
    word: 'depressed',
    definition: 'very sad and without hope',
    inSentence: "You mustn't let yourself get depressed.",
    synonyms: '',
    antonyms: '',
  },
];
