export const adverbs = [
  {
    type: 'adverbs',
    word: 'boldly',
    definition: 'in a brave, confident way; without being afraid to say what you feel or to take risks',
    inSentence: 'He stepped boldly forward to speak.',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'adverbs',
    word: 'brightly',
    definition: 'with a lot of light; with strong light',
    inSentence: 'The sun was shining brightly.',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'adverbs',
    word: 'cheerfully',
    definition: 'in a way that shows you are happy',
    inSentence: 'I could cheerfully have killed him when he said that.',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'adverbs',
    word: 'devotedly',
    definition: 'in a way that shows great love for somebody/something',
    inSentence: 'He was the first cousin of the Buddha, and was devotedly attached to him.',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'adverbs',
    word: 'elegantly',
    definition: 'in a way that is attractive and shows a good sense of style ',
    inSentence: 'He leaned elegantly against the door.',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'adverbs',
    word: 'faithfully',
    definition: 'in a way that shows true commitment; in a way that you can rely on',
    inSentence: 'The events were faithfully recorded in her diary.',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'adverbs',
    word: 'gracefully',
    definition: 'in an attractive way that shows control; showing a smooth, attractive form',
    inSentence: "The cathedral's white towers climb gracefully into the sky.",
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'adverbs',
    word: 'honestly',
    definition: 'used to emphasize that what you are saying is true, however surprising it may seem',
    inSentence: "I can't believe he got that money honestly.",
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'adverbs',
    word: 'justly',
    definition: 'in a way that most people consider to be morally fair and reasonable',
    inSentence: 'Her efforts were justly rewarded with a British Empire Medal.',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'adverbs',
    word: 'jealously',
    definition: 'in an angry or unhappy way because somebody you like or love is showing interest in somebody else',
    inSentence: 'Matt watched jealously as his girlfriend and Jake walked to class together.',
    synonyms: '',
    antonyms: '',
  },
];
