export const idioms = [
  {
    type: 'idioms',
    word: 'A blessing in disguise',
    definition: 'a good thing that seemed bad at first',
    inSentence: '',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'idioms',
    word: 'A dime a dozen',
    definition: 'Something common',
    inSentence: '',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'idioms',
    word: 'Beat around the bush',
    definition: 'Avoid saying what you mean, usually because it is uncomfortable',
    inSentence: '',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'idioms',
    word: 'Better late than never',
    definition: 'Better to arrive late than not to come at all',
    inSentence: '',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'idioms',
    word: 'Bite the bullet',
    definition: 'To get something over with because it is inevitable',
    inSentence: '',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'idioms',
    word: 'Cutting corners',
    definition: 'Doing something poorly in order to save time or money',
    inSentence: '',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'idioms',
    word: 'Get something out of your system',
    definition: "Do the thing you've been wanting to do so you can move on",
    inSentence: '',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'idioms',
    word: 'Go back to the drawing board',
    definition: 'Start over',
    inSentence: '',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'idioms',
    word: 'Let someone off the hook',
    definition: 'To not hold someone responsible for something',
    inSentence: '',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'idioms',
    word: 'Miss the boat',
    definition: "It's too late",
    inSentence: '',
    synonyms: '',
    antonyms: '',
  },
];
