export const verbs = [
  {
    type: 'verbs',
    word: 'do',
    definition: 'do something used to refer to actions that you do not mention by name or do not know about',
    inSentence: 'We will do what we can to help.',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'verbs',
    word: 'drink',
    definition: '[countable, uncountable] a liquid for drinking; an amount of a liquid that you drink',
    inSentence: 'Do you want a drink?',
    synonyms: 'make',
    antonyms: '',
  },
  {
    type: 'verbs',
    word: 'eat',
    definition: '[intransitive, transitive] to put food in your mouth, bite it and swallow it ',
    inSentence: 'I was too nervous to eat.',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'verbs',
    word: 'feel',
    definition: 'linking verb to experience a particular feeling or emotion',
    inSentence: 'Are you feeling comfortable?',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'verbs',
    word: 'fight',
    definition: '[intransitive, transitive] to take part in a war or battle against an enemy',
    inSentence: "Didn't we fight a war for freedom?",
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'verbs',
    word: 'find',
    definition: '[transitive] to discover somebody/something unexpectedly or by chance',
    inSentence: 'They found a car abandoned on top of the cliff.',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'verbs',
    word: 'go',
    definition: '[intransitive] to move or travel from one place to another',
    inSentence: 'I have to go to Rome on business.',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'verbs',
    word: 'hear',
    definition: '[intransitive, transitive] to be aware of sounds with your ears',
    inSentence: 'I could hear the sound of traffic in the background.',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'verbs',
    word: 'hit',
    definition: '[transitive] to bring your hand, or an object you are holding, against somebody/something quickly and with force',
    inSentence: 'She hit him with her umbrella.',
    synonyms: '',
    antonyms: '',
  },
  {
    type: 'verbs',
    word: 'lead',
    definition:
      '[intransitive, transitive] to go with or in front of a person or an animal to show the way or to make them go in the right direction',
    inSentence: 'The receptionist led the way to the boardroom.',
    synonyms: 'take',
    antonyms: '',
  },
];
